[project]
name = "ml-ops-hw05"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
]

[dependency-groups]
dev = [
    "apache-airflow~=3.1.5",
]
